#!/usr/local/bin/bash

root="$HOME/Library/Application Support/Sublime Text 3/Packages"
files=("zenburn" "MoveText" "TransposeCharacter" "Bracketeer" "Quickfind"
       "SimpleMovements" "StringEncode" "FileDiffs" "MarkAndMove" "ChangeQuotes"
       "ClipboardManager" "ApacheConf.tmLanguage" "Calculate" "SetSyntax"
       "DuplicateSelections" "ScreencastDirector" "TextFormatting" "INDY500"
       "Android" "MotionLookitup" "Groupy")

for folder in ${files[@]}
do
  if [[ -z "$out" ]]; then
    out=$(cat <<PACKAGEJSON
{
  "schema_version": "2.0",
  "packages": [
PACKAGEJSON
)
  else
    out="$out,"
  fi

  pushd "$root/$folder" > /dev/null

  latest_tag=$(git tag | sortver | tail -n 1)
  latest_version=${latest_tag:1}
  tag_date=$(git log --pretty=format:'%ci' -n 1 "$latest_tag")
  tag_date=${tag_date:0:19}

  package_json="$root/$folder/package.json"
  package=$(sed 's/^/    /' < "$package_json")

  name=$(json "$package_json" 'name')

  echo ">>> $name" 1>&2
  out=$(cat <<PACKAGEJSON
$out
$package
PACKAGEJSON
)
  popd > /dev/null
done

out=$(cat <<PACKAGEJSON
$out
  ]
}
PACKAGEJSON
)

if [[ -t 1 ]]; then
  echo "$out" > packages.json
else
  echo "$out"
fi

