#!/usr/bin/env bash

if [[ "$0" != "./test" ]]; then
  echo -e "\033[32mRight:\033[0m ./test"
  echo -e "\033[31mWrong:\033[0m source test"
  return 1
fi

files=`cat packages.json  | grep '"url"' | sed -E 's/^ +"url": "(.*)"$/\1/'`
ret=0
for url in $files
do
	echo -n "$url..."
  ok=`headers $url | head -n 1 | grep 'HTTP.*4'`
  if [[ -z "$ok" ]]; then
    echo -e "\033[32mOK\033[0m"
  else
    echo -e "\033[31;1mFAIL\033[0m"
    ret=1
  fi
done

exit $ret
